# Generated by Django 4.0.4 on 2022-09-20 10:54

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    User(user_name="Joe Silver", password="sheesh", email="joe@email.com").save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
